// <auto-generated />
using System;
using MedievalApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedievalApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918025737_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MedievalApi.Models.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DadosAnteriores")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados_anteriores");

                    b.Property<string>("DadosNovos")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados_novos");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip");

                    b.Property<int?>("RegistroId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("registro_id");

                    b.Property<string>("Tabela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("tabela");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm")
                        .HasDatabaseName("ix_auditoria_criado_em");

                    b.HasIndex("RegistroId")
                        .HasDatabaseName("ix_auditoria_registro_id");

                    b.HasIndex("Tabela")
                        .HasDatabaseName("ix_auditoria_tabela");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_auditoria_tipo");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_auditoria_usuario_id");

                    b.HasIndex("Tabela", "RegistroId")
                        .HasDatabaseName("ix_auditoria_tabela_registro");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.Cotacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataLimiteResposta")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_limite_resposta");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_solicitacao");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Rascunho")
                        .HasColumnName("status");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("DataLimiteResposta")
                        .HasDatabaseName("ix_cotacao_data_limite_resposta");

                    b.HasIndex("DataSolicitacao")
                        .HasDatabaseName("ix_cotacao_data_solicitacao");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_cotacao_status");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_cotacao_usuario_id");

                    b.ToTable("cotacao", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.CotacaoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CotacaoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cotacao_id");

                    b.Property<int?>("CotacaoItemFornecedorEscolhidoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cotacao_item_fornecedor_escolhido_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(14, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantidade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pendente")
                        .HasColumnName("status");

                    b.Property<int>("UnidadeMedidaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unidade_medida_id");

                    b.HasKey("Id");

                    b.HasIndex("CotacaoId")
                        .HasDatabaseName("ix_cotacao_item_cotacao_id");

                    b.HasIndex("CotacaoItemFornecedorEscolhidoId")
                        .HasDatabaseName("ix_cotacao_item_fornecedor_escolhido_id");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_cotacao_item_produto_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_cotacao_item_status");

                    b.HasIndex("UnidadeMedidaId")
                        .HasDatabaseName("ix_cotacao_item_unidade_medida_id");

                    b.ToTable("cotacao_item", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.CotacaoItemFornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CondicaoPagamento")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("condicao_pagamento");

                    b.Property<int>("CotacaoItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cotacao_item_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<int?>("PrazoEntregaDias")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prazo_entrega_dias");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(16, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId")
                        .HasDatabaseName("ix_cotacao_item_fornecedor_fornecedor_id");

                    b.HasIndex("CotacaoItemId", "FornecedorId")
                        .IsUnique()
                        .HasDatabaseName("ix_cotacao_item_fornecedor_unique");

                    b.ToTable("cotacao_item_fornecedor", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.Estoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("QuantidadeDisponivel")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("quantidade_disponivel");

                    b.Property<DateTime?>("UltimaEntrada")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ultima_entrada");

                    b.Property<DateTime?>("UltimaSaida")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ultima_saida");

                    b.Property<decimal>("ValorTotal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(16, 4)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId")
                        .IsUnique()
                        .HasDatabaseName("ix_estoque_produto_id");

                    b.HasIndex("QuantidadeDisponivel")
                        .HasDatabaseName("ix_estoque_quantidade_disponivel");

                    b.ToTable("estoque", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("complemento");

                    b.Property<string>("CondicaoPagamento")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("condicao_pagamento");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DiasEntrega")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("dias_entrega");

                    b.Property<string>("Documento")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("inscricao_estadual");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("logradouro");

                    b.Property<string>("NomeContato")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_contato");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("numero");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("razao_social");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_fornecedor_ativo");

                    b.HasIndex("Documento")
                        .HasDatabaseName("ix_fornecedor_documento");

                    b.HasIndex("NomeFantasia")
                        .HasDatabaseName("ix_fornecedor_nome_fantasia");

                    b.HasIndex("RazaoSocial")
                        .HasDatabaseName("ix_fornecedor_razao_social");

                    b.ToTable("fornecedor", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.GrupoProduto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_grupo_produto_ativo");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_grupo_produto_nome");

                    b.ToTable("grupo_produto", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("CustoUnitario")
                        .HasPrecision(16, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("custo_unitario");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_validade");

                    b.Property<int>("EstoqueId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estoque_id");

                    b.Property<string>("Lote")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("lote");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("origem");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(14, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("QuantidadeAnterior")
                        .HasPrecision(14, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantidade_anterior");

                    b.Property<decimal>("QuantidadePosterior")
                        .HasPrecision(14, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantidade_posterior");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("referencia_id");

                    b.Property<string>("ReferenciaTipo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("referencia_tipo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.Property<decimal?>("ValorTotal")
                        .HasPrecision(16, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm")
                        .HasDatabaseName("ix_movimentacao_estoque_criado_em");

                    b.HasIndex("EstoqueId")
                        .HasDatabaseName("ix_movimentacao_estoque_estoque_id");

                    b.HasIndex("Origem")
                        .HasDatabaseName("ix_movimentacao_estoque_origem");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_movimentacao_estoque_tipo");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_movimentacao_estoque_usuario_id");

                    b.HasIndex("ReferenciaTipo", "ReferenciaId")
                        .HasDatabaseName("ix_movimentacao_estoque_referencia");

                    b.ToTable("movimentacao_estoque", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.PedidoCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CotacaoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cotacao_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_pedido");

                    b.Property<DateTime?>("DataPrevistaEntrega")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_prevista_entrega");

                    b.Property<DateTime?>("DataRecebimento")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_recebimento");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Rascunho")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(16, 4)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("total");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("CotacaoId")
                        .HasDatabaseName("ix_pedido_compra_cotacao_id");

                    b.HasIndex("DataPedido")
                        .HasDatabaseName("ix_pedido_compra_data_pedido");

                    b.HasIndex("FornecedorId")
                        .HasDatabaseName("ix_pedido_compra_fornecedor_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_pedido_compra_status");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_pedido_compra_usuario_id");

                    b.ToTable("pedido_compra", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.PedidoCompraItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CotacaoItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cotacao_item_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<int>("PedidoCompraId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pedido_compra_id");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("QuantidadeRecebida")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("quantidade_recebida");

                    b.Property<decimal>("QuantidadeSolicitada")
                        .HasPrecision(14, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantidade_solicitada");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(16, 4)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("total");

                    b.Property<int>("UnidadeMedidaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unidade_medida_id");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(16, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id");

                    b.HasIndex("CotacaoItemId")
                        .HasDatabaseName("ix_pedido_compra_item_cotacao_item_id");

                    b.HasIndex("PedidoCompraId")
                        .HasDatabaseName("ix_pedido_compra_item_pedido_compra_id");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_pedido_compra_item_produto_id");

                    b.HasIndex("UnidadeMedidaId")
                        .HasDatabaseName("ix_pedido_compra_item_unidade_medida_id");

                    b.ToTable("pedido_compra_item", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("CustoMedioEstoque")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 4)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("custo_medio_estoque");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<decimal?>("EstoqueMaximo")
                        .HasPrecision(14, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("estoque_maximo");

                    b.Property<decimal>("EstoqueMinimo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("estoque_minimo");

                    b.Property<int>("GrupoProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_produto_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<decimal>("UltimoCusto")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 4)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("ultimo_custo");

                    b.Property<int>("UnidadeMedidaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unidade_medida_id");

                    b.Property<int?>("ValidadeDias")
                        .HasColumnType("INTEGER")
                        .HasColumnName("validade_dias");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_produto_ativo");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_produto_codigo")
                        .HasFilter("codigo IS NOT NULL");

                    b.HasIndex("GrupoProdutoId")
                        .HasDatabaseName("ix_produto_grupo_produto_id");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_produto_nome");

                    b.HasIndex("UnidadeMedidaId")
                        .HasDatabaseName("ix_produto_unidade_medida_id");

                    b.HasIndex("GrupoProdutoId", "Ativo")
                        .HasDatabaseName("ix_produto_grupo_produto_ativo");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.SaidaEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataSaida")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_saida");

                    b.Property<string>("Motivo")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("motivo");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Rascunho")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("DataSaida")
                        .HasDatabaseName("ix_saida_estoque_data_saida");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_saida_estoque_status");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_saida_estoque_tipo");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_saida_estoque_usuario_id");

                    b.ToTable("saida_estoque", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.SaidaEstoqueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("CustoTotal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(16, 4)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("custo_total");

                    b.Property<decimal>("CustoUnitario")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(16, 4)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("custo_unitario");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_validade");

                    b.Property<string>("Lote")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("lote");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(14, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantidade");

                    b.Property<int>("SaidaEstoqueId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("saida_estoque_id");

                    b.Property<int>("UnidadeMedidaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unidade_medida_id");

                    b.HasKey("Id");

                    b.HasIndex("DataValidade")
                        .HasDatabaseName("ix_saida_estoque_item_data_validade");

                    b.HasIndex("Lote")
                        .HasDatabaseName("ix_saida_estoque_item_lote");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_saida_estoque_item_produto_id");

                    b.HasIndex("SaidaEstoqueId")
                        .HasDatabaseName("ix_saida_estoque_item_saida_estoque_id");

                    b.HasIndex("UnidadeMedidaId")
                        .HasDatabaseName("ix_saida_estoque_item_unidade_medida_id");

                    b.ToTable("saida_estoque_item", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.UnidadeMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("sigla");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_unidade_medida_ativo");

                    b.HasIndex("Sigla")
                        .IsUnique()
                        .HasDatabaseName("ix_unidade_medida_sigla");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_unidade_medida_tipo");

                    b.ToTable("unidade_medida", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("GrupoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("grupo_usuario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Ativo")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ultimo_login");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_email");

                    b.HasIndex("GrupoUsuario")
                        .HasDatabaseName("ix_usuario_grupo_usuario");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_usuario_status");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.Auditoria", b =>
                {
                    b.HasOne("MedievalApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_auditoria_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MedievalApi.Models.Cotacao", b =>
                {
                    b.HasOne("MedievalApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cotacao_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MedievalApi.Models.CotacaoItem", b =>
                {
                    b.HasOne("MedievalApi.Models.Cotacao", "Cotacao")
                        .WithMany("Itens")
                        .HasForeignKey("CotacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cotacao_item_cotacao");

                    b.HasOne("MedievalApi.Models.CotacaoItemFornecedor", "CotacaoItemFornecedorEscolhido")
                        .WithMany()
                        .HasForeignKey("CotacaoItemFornecedorEscolhidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cotacao_item_fornecedor_escolhido");

                    b.HasOne("MedievalApi.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cotacao_item_produto");

                    b.HasOne("MedievalApi.Models.UnidadeMedida", "UnidadeMedida")
                        .WithMany()
                        .HasForeignKey("UnidadeMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cotacao_item_unidade_medida");

                    b.Navigation("Cotacao");

                    b.Navigation("CotacaoItemFornecedorEscolhido");

                    b.Navigation("Produto");

                    b.Navigation("UnidadeMedida");
                });

            modelBuilder.Entity("MedievalApi.Models.CotacaoItemFornecedor", b =>
                {
                    b.HasOne("MedievalApi.Models.CotacaoItem", "CotacaoItem")
                        .WithMany()
                        .HasForeignKey("CotacaoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cotacao_item_fornecedor_cotacao_item");

                    b.HasOne("MedievalApi.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cotacao_item_fornecedor_fornecedor");

                    b.Navigation("CotacaoItem");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("MedievalApi.Models.Estoque", b =>
                {
                    b.HasOne("MedievalApi.Models.Produto", "Produto")
                        .WithOne("Estoque")
                        .HasForeignKey("MedievalApi.Models.Estoque", "ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estoque_produto");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("MedievalApi.Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("MedievalApi.Models.Estoque", "Estoque")
                        .WithMany()
                        .HasForeignKey("EstoqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacao_estoque_estoque");

                    b.HasOne("MedievalApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacao_estoque_usuario");

                    b.Navigation("Estoque");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MedievalApi.Models.PedidoCompra", b =>
                {
                    b.HasOne("MedievalApi.Models.Cotacao", "Cotacao")
                        .WithMany()
                        .HasForeignKey("CotacaoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pedido_compra_cotacao");

                    b.HasOne("MedievalApi.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_compra_fornecedor");

                    b.HasOne("MedievalApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_compra_usuario");

                    b.Navigation("Cotacao");

                    b.Navigation("Fornecedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MedievalApi.Models.PedidoCompraItem", b =>
                {
                    b.HasOne("MedievalApi.Models.CotacaoItem", "CotacaoItem")
                        .WithMany()
                        .HasForeignKey("CotacaoItemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pedido_compra_item_cotacao_item");

                    b.HasOne("MedievalApi.Models.PedidoCompra", "PedidoCompra")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_compra_item_pedido_compra");

                    b.HasOne("MedievalApi.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_compra_item_produto");

                    b.HasOne("MedievalApi.Models.UnidadeMedida", "UnidadeMedida")
                        .WithMany()
                        .HasForeignKey("UnidadeMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_compra_item_unidade_medida");

                    b.Navigation("CotacaoItem");

                    b.Navigation("PedidoCompra");

                    b.Navigation("Produto");

                    b.Navigation("UnidadeMedida");
                });

            modelBuilder.Entity("MedievalApi.Models.Produto", b =>
                {
                    b.HasOne("MedievalApi.Models.GrupoProduto", "GrupoProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("GrupoProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_produto_grupo_produto");

                    b.HasOne("MedievalApi.Models.UnidadeMedida", "UnidadeMedida")
                        .WithMany("Produtos")
                        .HasForeignKey("UnidadeMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_produto_unidade_medida");

                    b.Navigation("GrupoProduto");

                    b.Navigation("UnidadeMedida");
                });

            modelBuilder.Entity("MedievalApi.Models.SaidaEstoque", b =>
                {
                    b.HasOne("MedievalApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_saida_estoque_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MedievalApi.Models.SaidaEstoqueItem", b =>
                {
                    b.HasOne("MedievalApi.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_saida_estoque_item_produto");

                    b.HasOne("MedievalApi.Models.SaidaEstoque", "SaidaEstoque")
                        .WithMany("Itens")
                        .HasForeignKey("SaidaEstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saida_estoque_item_saida_estoque");

                    b.HasOne("MedievalApi.Models.UnidadeMedida", "UnidadeMedida")
                        .WithMany()
                        .HasForeignKey("UnidadeMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_saida_estoque_item_unidade_medida");

                    b.Navigation("Produto");

                    b.Navigation("SaidaEstoque");

                    b.Navigation("UnidadeMedida");
                });

            modelBuilder.Entity("MedievalApi.Models.Cotacao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("MedievalApi.Models.GrupoProduto", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("MedievalApi.Models.PedidoCompra", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("MedievalApi.Models.Produto", b =>
                {
                    b.Navigation("Estoque");
                });

            modelBuilder.Entity("MedievalApi.Models.SaidaEstoque", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("MedievalApi.Models.UnidadeMedida", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
