// <auto-generated />
using System;
using MedievalApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedievalApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MedievalApi.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_categoria_ativo");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_categoria_nome");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("CustoMedioEstoque")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 4)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("custo_medio_estoque");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<decimal?>("EstoqueMaximo")
                        .HasPrecision(14, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("estoque_maximo");

                    b.Property<decimal>("EstoqueMinimo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("estoque_minimo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<decimal>("UltimoCusto")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 4)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("ultimo_custo");

                    b.Property<int>("UnidadeMedidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_medida_id");

                    b.Property<int?>("ValidadeDias")
                        .HasColumnType("INTEGER")
                        .HasColumnName("validade_dias");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_produto_ativo");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_produto_categoria_id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_produto_codigo")
                        .HasFilter("codigo IS NOT NULL");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_produto_nome");

                    b.HasIndex("UnidadeMedidaId")
                        .HasDatabaseName("ix_produto_unidade_medida_id");

                    b.HasIndex("CategoriaId", "Ativo")
                        .HasDatabaseName("ix_produto_categoria_ativo");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.UnidadeMedida", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("sigla");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_unidade_medida_ativo");

                    b.HasIndex("Sigla")
                        .IsUnique()
                        .HasDatabaseName("ix_unidade_medida_sigla");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_unidade_medida_tipo");

                    b.ToTable("unidade_medida", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("GrupoUsuario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Consulta")
                        .HasColumnName("grupo_usuario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Ativo")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("TEXT")
                        .HasColumnName("ultimo_login");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_email");

                    b.HasIndex("GrupoUsuario")
                        .HasDatabaseName("ix_usuario_grupo_usuario");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_usuario_status");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("MedievalApi.Models.Produto", b =>
                {
                    b.HasOne("MedievalApi.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_produto_categoria");

                    b.HasOne("MedievalApi.Models.UnidadeMedida", "UnidadeMedida")
                        .WithMany("Produtos")
                        .HasForeignKey("UnidadeMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_produto_unidade_medida");

                    b.Navigation("Categoria");

                    b.Navigation("UnidadeMedida");
                });

            modelBuilder.Entity("MedievalApi.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("MedievalApi.Models.UnidadeMedida", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
