CREATE TYPE "usuario_status" AS ENUM (
  'ativo',
  'inativo'
);

CREATE TYPE "grupo_usuario" AS ENUM (
  'administrador',
  'consulta'
);

CREATE TYPE "status_cotacao_item" AS ENUM (
  'pendente',
  'selecionado',
  'cancelado'
);

CREATE TYPE "status_pedido_compra" AS ENUM (
  'rascunho',
  'enviado',
  'parcialmente_recebido',
  'recebido',
  'cancelado'
);

CREATE TYPE "tipo_movimentacao_estoque" AS ENUM (
  'entrada',
  'saida',
  'ajuste',
  'perda',
  'devolucao'
);

CREATE TYPE "origem_movimentacao" AS ENUM (
  'pedido_compra',
  'saida_estoque',
  'ajuste_manual',
  'inventario',
  'devolucao',
  'perda'
);

CREATE TYPE "tipo_saida_estoque" AS ENUM (
  'consumo',
  'perda',
  'vencimento',
  'devolucao',
  'ajuste',
  'outro'
);

CREATE TYPE "status_saida_estoque" AS ENUM (
  'rascunho',
  'confirmada',
  'cancelada'
);

CREATE TYPE "tipo_auditoria" AS ENUM (
  'INSERT',
  'UPDATE',
  'DELETE',
  'LOGIN',
  'LOGOUT',
  'OUTRO'
);

CREATE TYPE "status_cotacao" AS ENUM (
  'rascunho',
  'enviada',
  'em_resposta',
  'encerrada',
  'cancelada'
);

CREATE TABLE "usuario" (
  "usuario_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(150) NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "senha_hash" varchar(255) NOT NULL,
  "grupo_usuario" grupo_usuario NOT NULL DEFAULT 'administrador',
  "status" usuario_status NOT NULL DEFAULT 'ativo',
  "ultimo_login" timestamp,
  "criado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "categoria" (
  "categoria_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) UNIQUE NOT NULL,
  "descricao" varchar(255),
  "ativo" boolean NOT NULL DEFAULT true,
  "criado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "produto" (
  "produto_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categoria_id" bigint NOT NULL,
  "unidade_medida_id" bigint NOT NULL,
  "codigo" varchar(50) UNIQUE,
  "nome" varchar(150) NOT NULL,
  "descricao" varchar(255),
  "estoque_minimo" decimal(14,3) NOT NULL DEFAULT 0,
  "estoque_maximo" decimal(14,3),
  "custo_medio_estoque" decimal(14,4) NOT NULL DEFAULT 0,
  "ultimo_custo" decimal(14,4) NOT NULL DEFAULT 0,
  "validade_dias" int,
  "ativo" boolean NOT NULL DEFAULT true,
  "criado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "unidade_medida" (
  "unidade_medida_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "sigla" varchar(20) UNIQUE NOT NULL,
  "tipo" varchar(50) NOT NULL,
  "ativo" boolean NOT NULL DEFAULT true,
  "criado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "fornecedor" (
  "fornecedor_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "razao_social" varchar(200) NOT NULL,
  "nome_fantasia" varchar(200),
  "documento" varchar(30),
  "inscricao_estadual" varchar(30),
  "email" varchar(150),
  "telefone" varchar(30),
  "nome_contato" varchar(150),
  "cep" varchar(10),
  "logradouro" varchar(200),
  "numero" varchar(20),
  "complemento" varchar(100),
  "bairro" varchar(100),
  "cidade" varchar(100),
  "estado" varchar(2),
  "dias_entrega" varchar(50),
  "condicao_pagamento" varchar(150),
  "ativo" boolean NOT NULL DEFAULT true,
  "criado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "cotacao" (
  "cotacao_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" bigint NOT NULL,
  "data_solicitacao" date NOT NULL,
  "data_limite_resposta" date,
  "status" status_cotacao NOT NULL DEFAULT 'rascunho',
  "observacao" text,
  "criado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "cotacao_item" (
  "cotacao_item_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cotacao_id" bigint NOT NULL,
  "produto_id" bigint NOT NULL,
  "unidade_medida_id" bigint NOT NULL,
  "quantidade" decimal(14,3) NOT NULL,
  "cotacao_item_fornecedor_escolhido_id" bigint,
  "status" status_cotacao_item NOT NULL DEFAULT 'pendente',
  "observacao" varchar(255),
  "criado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "cotacao_item_fornecedor" (
  "cotacao_item_fornecedor_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cotacao_item_id" bigint NOT NULL,
  "fornecedor_id" bigint NOT NULL,
  "valor_unitario" decimal(16,4) NOT NULL,
  "prazo_entrega_dias" int,
  "condicao_pagamento" varchar(150),
  "observacao" varchar(255),
  "criado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "pedido_compra" (
  "pedido_compra_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fornecedor_id" bigint NOT NULL,
  "usuario_id" bigint NOT NULL,
  "cotacao_id" bigint,
  "data_pedido" date NOT NULL,
  "data_prevista_entrega" date,
  "data_recebimento" timestamp,
  "status" status_pedido_compra NOT NULL DEFAULT 'rascunho',
  "total" decimal(16,4) NOT NULL DEFAULT 0,
  "observacao" text,
  "criado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "pedido_compra_item" (
  "pedido_compra_item_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pedido_compra_id" bigint NOT NULL,
  "produto_id" bigint NOT NULL,
  "unidade_medida_id" bigint NOT NULL,
  "cotacao_item_id" bigint,
  "quantidade_solicitada" decimal(14,3) NOT NULL,
  "quantidade_recebida" decimal(14,3) NOT NULL DEFAULT 0,
  "valor_unitario" decimal(16,4) NOT NULL,
  "total" decimal(16,4) NOT NULL DEFAULT 0,
  "observacao" varchar(255),
  "criado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "estoque" (
  "estoque_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "produto_id" bigint UNIQUE NOT NULL,
  "quantidade_disponivel" decimal(14,3) NOT NULL DEFAULT 0,
  "valor_total" decimal(16,4) NOT NULL DEFAULT 0,
  "ultima_entrada" timestamp,
  "ultima_saida" timestamp,
  "atualizado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "saida_estoque" (
  "saida_estoque_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" bigint NOT NULL,
  "data_saida" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "tipo" tipo_saida_estoque NOT NULL,
  "status" status_saida_estoque NOT NULL DEFAULT 'rascunho',
  "motivo" varchar(255),
  "observacao" text,
  "criado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "saida_estoque_item" (
  "saida_estoque_item_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "saida_estoque_id" bigint NOT NULL,
  "produto_id" bigint NOT NULL,
  "unidade_medida_id" bigint NOT NULL,
  "quantidade" decimal(14,3) NOT NULL,
  "custo_unitario" decimal(16,4) NOT NULL DEFAULT 0,
  "custo_total" decimal(16,4) NOT NULL DEFAULT 0,
  "lote" varchar(100),
  "data_validade" date,
  "observacao" varchar(255),
  "criado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "movimentacao_estoque" (
  "movimentacao_estoque_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estoque_id" bigint NOT NULL,
  "usuario_id" bigint NOT NULL,
  "tipo" tipo_movimentacao_estoque NOT NULL,
  "origem" origem_movimentacao NOT NULL,
  "quantidade" decimal(14,3) NOT NULL,
  "quantidade_anterior" decimal(14,3) NOT NULL,
  "quantidade_posterior" decimal(14,3) NOT NULL,
  "custo_unitario" decimal(16,4),
  "valor_total" decimal(16,4),
  "lote" varchar(100),
  "data_validade" date,
  "referencia_id" bigint,
  "referencia_tipo" varchar(50),
  "observacao" varchar(255),
  "criado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "auditoria" (
  "auditoria_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" bigint,
  "tabela" varchar(100) NOT NULL,
  "registro_id" bigint,
  "tipo" tipo_auditoria NOT NULL,
  "dados_anteriores" json,
  "dados_novos" json,
  "ip" varchar(45),
  "user_agent" varchar(500),
  "criado_em" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE UNIQUE INDEX ON "usuario" ("email");

CREATE INDEX ON "usuario" ("grupo_usuario");

CREATE INDEX ON "usuario" ("status");

CREATE UNIQUE INDEX ON "categoria" ("nome");

CREATE INDEX ON "categoria" ("ativo");

CREATE UNIQUE INDEX ON "produto" ("codigo");

CREATE INDEX ON "produto" ("nome");

CREATE INDEX ON "produto" ("categoria_id");

CREATE INDEX ON "produto" ("unidade_medida_id");

CREATE INDEX ON "produto" ("ativo");

CREATE UNIQUE INDEX ON "unidade_medida" ("sigla");

CREATE INDEX ON "unidade_medida" ("tipo");

CREATE INDEX ON "unidade_medida" ("ativo");

CREATE INDEX ON "fornecedor" ("documento");

CREATE INDEX ON "fornecedor" ("razao_social");

CREATE INDEX ON "fornecedor" ("nome_fantasia");

CREATE INDEX ON "fornecedor" ("ativo");

CREATE INDEX ON "cotacao" ("usuario_id");

CREATE INDEX ON "cotacao" ("status");

CREATE INDEX ON "cotacao" ("data_solicitacao");

CREATE INDEX ON "cotacao" ("data_limite_resposta");

CREATE INDEX ON "cotacao_item" ("cotacao_id");

CREATE INDEX ON "cotacao_item" ("produto_id");

CREATE INDEX ON "cotacao_item" ("unidade_medida_id");

CREATE INDEX ON "cotacao_item" ("cotacao_item_fornecedor_escolhido_id");

CREATE INDEX ON "cotacao_item" ("status");

CREATE UNIQUE INDEX ON "cotacao_item_fornecedor" ("cotacao_item_id", "fornecedor_id");

CREATE INDEX ON "pedido_compra" ("fornecedor_id");

CREATE INDEX ON "pedido_compra" ("usuario_id");

CREATE INDEX ON "pedido_compra" ("cotacao_id");

CREATE INDEX ON "pedido_compra" ("status");

CREATE INDEX ON "pedido_compra" ("data_pedido");

CREATE INDEX ON "pedido_compra_item" ("pedido_compra_id");

CREATE INDEX ON "pedido_compra_item" ("produto_id");

CREATE INDEX ON "pedido_compra_item" ("unidade_medida_id");

CREATE UNIQUE INDEX ON "estoque" ("produto_id");

CREATE INDEX ON "estoque" ("quantidade_disponivel");

CREATE INDEX ON "saida_estoque" ("usuario_id");

CREATE INDEX ON "saida_estoque" ("data_saida");

CREATE INDEX ON "saida_estoque" ("tipo");

CREATE INDEX ON "saida_estoque" ("status");

CREATE INDEX ON "saida_estoque_item" ("saida_estoque_id");

CREATE INDEX ON "saida_estoque_item" ("produto_id");

CREATE INDEX ON "saida_estoque_item" ("unidade_medida_id");

CREATE INDEX ON "saida_estoque_item" ("lote");

CREATE INDEX ON "saida_estoque_item" ("data_validade");

CREATE INDEX ON "movimentacao_estoque" ("estoque_id");

CREATE INDEX ON "movimentacao_estoque" ("usuario_id");

CREATE INDEX ON "movimentacao_estoque" ("tipo");

CREATE INDEX ON "movimentacao_estoque" ("origem");

CREATE INDEX ON "movimentacao_estoque" ("criado_em");

CREATE INDEX ON "movimentacao_estoque" ("referencia_tipo", "referencia_id");

CREATE INDEX ON "auditoria" ("usuario_id");

CREATE INDEX ON "auditoria" ("tabela");

CREATE INDEX ON "auditoria" ("registro_id");

CREATE INDEX ON "auditoria" ("tipo");

CREATE INDEX ON "auditoria" ("criado_em");

ALTER TABLE "produto" ADD FOREIGN KEY ("categoria_id") REFERENCES "categoria" ("categoria_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "produto" ADD FOREIGN KEY ("unidade_medida_id") REFERENCES "unidade_medida" ("unidade_medida_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "estoque" ADD FOREIGN KEY ("produto_id") REFERENCES "produto" ("produto_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cotacao" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cotacao_item" ADD FOREIGN KEY ("cotacao_id") REFERENCES "cotacao" ("cotacao_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cotacao_item" ADD FOREIGN KEY ("produto_id") REFERENCES "produto" ("produto_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cotacao_item" ADD FOREIGN KEY ("unidade_medida_id") REFERENCES "unidade_medida" ("unidade_medida_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cotacao_item" ADD FOREIGN KEY ("cotacao_item_fornecedor_escolhido_id") REFERENCES "cotacao_item_fornecedor" ("cotacao_item_fornecedor_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cotacao_item_fornecedor" ADD FOREIGN KEY ("cotacao_item_id") REFERENCES "cotacao_item" ("cotacao_item_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cotacao_item_fornecedor" ADD FOREIGN KEY ("fornecedor_id") REFERENCES "fornecedor" ("fornecedor_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_compra" ADD FOREIGN KEY ("cotacao_id") REFERENCES "cotacao" ("cotacao_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_compra" ADD FOREIGN KEY ("fornecedor_id") REFERENCES "fornecedor" ("fornecedor_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_compra" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_compra_item" ADD FOREIGN KEY ("pedido_compra_id") REFERENCES "pedido_compra" ("pedido_compra_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_compra_item" ADD FOREIGN KEY ("cotacao_item_id") REFERENCES "cotacao_item" ("cotacao_item_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_compra_item" ADD FOREIGN KEY ("produto_id") REFERENCES "produto" ("produto_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_compra_item" ADD FOREIGN KEY ("unidade_medida_id") REFERENCES "unidade_medida" ("unidade_medida_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "saida_estoque" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "saida_estoque_item" ADD FOREIGN KEY ("saida_estoque_id") REFERENCES "saida_estoque" ("saida_estoque_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "saida_estoque_item" ADD FOREIGN KEY ("produto_id") REFERENCES "produto" ("produto_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "saida_estoque_item" ADD FOREIGN KEY ("unidade_medida_id") REFERENCES "unidade_medida" ("unidade_medida_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movimentacao_estoque" ADD FOREIGN KEY ("estoque_id") REFERENCES "estoque" ("estoque_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movimentacao_estoque" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "auditoria" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;
